---
- name: Donwload Apache Tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_install_dir }}"

- name: Unpack Tomcat
  unarchive:
    src: "{{ tomcat_install_dir }}/{{ tomcat_download_url | basename }}"
    dest: "{{ tomcat_install_dir }}"
    owner: "{{ tomcat_linux_user }}"

- name: Create manager credentials
  blockinfile:
    dest: "{{ catalina_home }}/conf/tomcat-users.xml"
    insertbefore: </tomcat-users>
    block: |
      <role rolename="manager-gui"/>
      <user username="{{ tomcat_manager_gui_username }}" password="{{ tomcat_manager_gui_password }}" roles="manager-gui"/>

- name: Create Catalina/localhost folder
  file:
    dest: "{{ item }}"
    state: directory
    mode: '775'
    owner: "{{ tomcat_linux_user }}"
    group: "{{ tomcat_linux_user }}"
  with_items:
    - "{{ catalina_home }}/conf/Catalina"
    - "{{ catalina_home }}/conf/Catalina/localhost"

- name: Allow remote access
  copy:
    dest: "{{ catalina_home }}/conf/Catalina/localhost/manager.xml"
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <Context privileged="true" antiResourceLocking="false" docBase="${catalina.home}/webapps/manager">
          <Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="^.*$" />
      </Context>

- name: Create Tomcat Service
  copy:
    dest: /lib/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Tomcat Service
      After=syslog.target network.target

      [Service]
      Type=forking

      Environment=CATALINA_PID={{ catalina_home }}/temp/tomcat.pid
      Environment=CATALINA_HOME={{ catalina_home }}
      Environment=CATALINA_BASE={{ catalina_home }}
      Environment=JPDA_ADDRESS=0.0.0.0:8088

      ExecStart={{ catalina_home }}/bin/catalina.sh jpda start
      ExecStop=/bin/kill -15 $MAINPID

      User={{ tomcat_linux_user }}

      [Install]
      WantedBy=multi-user.target

- name: Start Tomcat
  service:
    name: tomcat
    enabled: yes
    state: started
